spring.application.name=ai-service
server.port=8085

# Clé secrète de l'API Grok (x.ai) fournie par la PR
grok.api.key=${GROQ_API_KEY}
grok.model=llama-3.3-70b-versatile
groq.api.max-tokens=500
grok.api.url=https://api.groq.com/openai/v1/chat/completions

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

