spring.application.name=community-service

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/aeris
spring.datasource.username=aeris
spring.datasource.password=passer123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
